# Pull base image for python
FROM python:3.8-slim

# Set working directory in Image
WORKDIR /app

# Copy the current directory contents at /app in the Image
COPY . /app

# Run the application
CMD ["python" , "app.py"]